# This workflow publishes a selected blog draft to WordPress.com
name: Publish Blog to WordPress

on:
  workflow_dispatch:
    inputs:
      blog_file:
        description: 'Path to the markdown blog file to publish (e.g. drafts/2025-06-29-My_Blog.md)'
        required: true

jobs:
  publish-to-wordpress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BLOG_REPO || github.repository }}
          token: ${{ secrets.BLOG_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          path: blogrepo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv markdown

      - name: Publish to WordPress
        env:
          WP_ACCESS_TOKEN: ${{ secrets.WP_ACCESS_TOKEN }}
          WP_SITE_ID: ${{ secrets.WP_SITE_ID }}
          BLOG_FILE: blogrepo/${{ github.event.inputs.blog_file }}
        run: |
          python publish_to_wordpress.py
