
# This workflow publishes a selected blog draft to dev.to
name: Publish Blog to dev.to

on:
  workflow_dispatch:
    inputs:
      blog_file:
        description: 'Path to the markdown blog file to publish (e.g. drafts/2025-06-29-My_Blog.md)'
        required: true

jobs:
  publish-to-devto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      - name: Checkout blog repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.BLOG_REPO }}
          token: ${{ secrets.BLOG_REPO_TOKEN }}
          path: blogrepo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv markdown

      - name: Publish to dev.to
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
          BLOG_FILE: blogrepo/${{ github.event.inputs.blog_file }}
        run: |
          python publish_to_devto.py
